# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.entry import Entry  # noqa: F401,E501
from swagger_server import util


class Entries(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, count: int=None, items: List[Entry]=None, offset: int=None, offset_next: int=None, table_uri: str=None):  # noqa: E501
        """Entries - a model defined in Swagger

        :param count: The count of this Entries.  # noqa: E501
        :type count: int
        :param items: The items of this Entries.  # noqa: E501
        :type items: List[Entry]
        :param offset: The offset of this Entries.  # noqa: E501
        :type offset: int
        :param offset_next: The offset_next of this Entries.  # noqa: E501
        :type offset_next: int
        :param table_uri: The table_uri of this Entries.  # noqa: E501
        :type table_uri: str
        """
        self.swagger_types = {
            'count': int,
            'items': List[Entry],
            'offset': int,
            'offset_next': int,
            'table_uri': str
        }

        self.attribute_map = {
            'count': 'count',
            'items': 'items',
            'offset': 'offset',
            'offset_next': 'offset_next',
            'table_uri': 'table_uri'
        }

        self._count = count
        self._items = items
        self._offset = offset
        self._offset_next = offset_next
        self._table_uri = table_uri

    @classmethod
    def from_dict(cls, dikt) -> 'Entries':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Entries of this Entries.  # noqa: E501
        :rtype: Entries
        """
        return util.deserialize_model(dikt, cls)

    @property
    def count(self) -> int:
        """Gets the count of this Entries.

        Total entries count, independently of limit.  # noqa: E501

        :return: The count of this Entries.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count: int):
        """Sets the count of this Entries.

        Total entries count, independently of limit.  # noqa: E501

        :param count: The count of this Entries.
        :type count: int
        """

        self._count = count

    @property
    def items(self) -> List[Entry]:
        """Gets the items of this Entries.


        :return: The items of this Entries.
        :rtype: List[Entry]
        """
        return self._items

    @items.setter
    def items(self, items: List[Entry]):
        """Sets the items of this Entries.


        :param items: The items of this Entries.
        :type items: List[Entry]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items

    @property
    def offset(self) -> int:
        """Gets the offset of this Entries.

        Current offset (eg. entries 50 to 99)  # noqa: E501

        :return: The offset of this Entries.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset: int):
        """Sets the offset of this Entries.

        Current offset (eg. entries 50 to 99)  # noqa: E501

        :param offset: The offset of this Entries.
        :type offset: int
        """
        if offset is None:
            raise ValueError("Invalid value for `offset`, must not be `None`")  # noqa: E501

        self._offset = offset

    @property
    def offset_next(self) -> int:
        """Gets the offset_next of this Entries.

        Offset for the next page (eg. entries from 100 to 149). This could be a link too in HATEOAS.  # noqa: E501

        :return: The offset_next of this Entries.
        :rtype: int
        """
        return self._offset_next

    @offset_next.setter
    def offset_next(self, offset_next: int):
        """Sets the offset_next of this Entries.

        Offset for the next page (eg. entries from 100 to 149). This could be a link too in HATEOAS.  # noqa: E501

        :param offset_next: The offset_next of this Entries.
        :type offset_next: int
        """
        if offset_next is None:
            raise ValueError("Invalid value for `offset_next`, must not be `None`")  # noqa: E501

        self._offset_next = offset_next

    @property
    def table_uri(self) -> str:
        """Gets the table_uri of this Entries.


        :return: The table_uri of this Entries.
        :rtype: str
        """
        return self._table_uri

    @table_uri.setter
    def table_uri(self, table_uri: str):
        """Sets the table_uri of this Entries.


        :param table_uri: The table_uri of this Entries.
        :type table_uri: str
        """

        self._table_uri = table_uri
