# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Timestampa(Model):

    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, timestamp: datetime=None):  # noqa: E501
        """Timestampa - a model defined in Swagger

        :param timestamp: The timestamp of this Timestampa.  # noqa: E501
        :type timestamp: datetime
        """
        self.swagger_types = {
            'timestamp': datetime
        }

        self.attribute_map = {
            'timestamp': 'timestamp'
        }

        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'Timestampa':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Timestampa of this Timestampa.  # noqa: E501
        :rtype: Timestampa
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this Timestampa.


        :return: The timestamp of this Timestampa.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this Timestampa.


        :param timestamp: The timestamp of this Timestampa.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
